### ISSUE TITLE
no exported field

### ISSUE THREAD

**Issue by DroppingLight** [Nik-U/pbc#2]
I define a struct like:
type BswabePub struct{
	/*
	 * A public key
	 */
	PairingDesc string	`json:"PairingDesc"`
	P *pbc.Pairing						`json:"P"`
	G *pbc.Element				/* G_1 */		`json:"G"`
	H *pbc.Element				/* G_1 */		`json:"H"`
	F *pbc.Element				/* G_1 */			`json:"F"`
	Gp *pbc.Element				/* G_2 */			`json:"Gp"`
	G_hat_alpha *pbc.Element	/* G_T */		`json:"G_hat_alpha"`
}

but when I try to save the data of my pub-key, the json.Marshal() can not export all the member,like P and G [ gob can not work either]. The struct of Element has private member, so I can not save the complete data. I don't know how to solve this.Thank you!

**Comment by Nik-U** [comment]
PBC elements are not directly exportable in this way because they need to be unmarshaled within the context of a `Pairing`. Additionally, you need to specify the group when unmarshaling. This means that you need to write the marshaling and unmarshaling code yourself in a way that makes sense for your application. The library provides several different ways to export elements, such as through `fmt` or as compressed bytes.

Generally speaking, the Go PBC wrapper is a thin layer around the C library, so many of the same techniques apply. For the BSW ABE scheme, take a look at how the original authors did it in `libbswabe-0.9/misc.c`. For serializing to JSON in Go, you could try something like this:

```go
type BswAbePub struct{
	PairingDesc string
	P *pbc.Pairing
	G, H, F *pbc.Element
	Gp *pbc.Element
	GHatAlpha *pbc.Element
}

type BswAbePubPacket struct {
	Params string
	G, H, F []byte
	Gp []byte
	GHatAlpha []byte
}

func (s BswAbePub) MarshalJSON() (text []byte, err error) {
	return json.Marshal(BswAbePubPacket{
		Params: s.PairingDesc,
		G: s.G.CompressedBytes(),
		H: s.H.CompressedBytes(),
		F: s.F.CompressedBytes(),
		Gp: s.Gp.CompressedBytes(),
		GHatAlpha: s.GHatAlpha.Bytes(),
	})
}

func (s *BswAbePub) UnmarshalJSON(text []byte) error {
	var packet BswAbePubPacket
	err := json.Unmarshal(text, &packet)
	if err != nil {
		return err
	}

	s.PairingDesc = packet.Params
	s.P, err = pbc.NewPairingFromString(s.PairingDesc)
	if err != nil {
		return err
	}

	s.G = s.P.NewG1().SetCompressedBytes(packet.G)
	s.H = s.P.NewG1().SetCompressedBytes(packet.H)
	s.F = s.P.NewG1().SetCompressedBytes(packet.F)
	s.Gp = s.P.NewG2().SetCompressedBytes(packet.Gp)
	s.GHatAlpha = s.P.NewGT().SetBytes(packet.GHatAlpha)
	return nil
}
```

The following code would do key generation, serializing, and deserializing (example only... this code has no error checking, and I haven't checked its correctness):

```go
var pub BswAbePub
pub.PairingDesc = "type a\nq 8780710799663312522437781984754049815806883199414208211028653399266475630880222957078625179422662221423155858769582317459277713367317481324925129998224791\nh 12016012264891146079388821366740534204802954401251311822919615131047207289359704531102844802183906537786776\nr 730750818665451621361119245571504901405976559617\nexp2 159\nexp1 107\nsign1 1\nsign0 1\n"
pub.P, _ = pbc.NewPairingFromString(pub.PairingDesc)

pub.G = pub.P.NewG1().Rand()
pub.Gp = pub.P.NewG2().Rand()

beta := pub.P.NewZr().Rand()
pub.H = pub.P.NewG1().PowZn(pub.G, beta)

oneOverBeta := pub.P.NewZr().Invert(beta)
pub.F = pub.P.NewG1().PowZn(pub.G, oneOverBeta)

alpha := pub.P.NewZr().Rand()
gAlpha := pub.P.NewG2().PowZn(pub.Gp, alpha)
pub.GHatAlpha = pub.P.NewGT().Pair(pub.G, gAlpha)

encoded, _ := json.Marshal(pub)

var decoded BswAbePub
json.Unmarshal(encoded, &decoded)
```
You should also ask yourself whether you _really_ want to include the pairing parameters in the JSON, or if it is acceptable to hard-code them in your application; see the SignBLS example in the PBC Go wrapper documentation for a high-level demonstration of how protocols can be implemented.

**Comment by DroppingLight** [comment]
@Nik-U I am so thankful for the time you took to help with my issue.
