### ISSUE TITLE
serializing `Power`

### ISSUE THREAD

**Issue by bl4ck5un** [Nik-U/pbc#3]
Is there a way to serialize the preprocessing outputs (i.e. [Power](https://github.com/Nik-U/pbc/blob/master/element_arith.go#L358))?

**Comment by Nik-U** [comment]
Unfortunately it does not seem to be possible since [pbc](https://github.com/blynn/pbc) does not expose the internals of preprocessing structs. Adding support for it in the Go wrapper would involve making some assumptions about the contents of void pointers and pbc internals that would be quite brittle.

If the pbc project adds serialization support for `element_pp_t` then the Go wrapper would certainly expose that functionality. In the meantime, the only option is to re-compute the information every time after deserializing the element.

**Comment by bl4ck5un** [comment]
that's unfortunate. it could have been a big performance boost for my application. thanks for the info.
