### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by lijiangt** [Nik-U/pbc#4]
Frequent calls run for dozens of minutes to a few hours will crash, the exception stack is as follows, each crash occurs in pairing.go line 65：

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x429289e]

runtime stack:
runtime.throw(0x40fbc00, 0x2a)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 5 [syscall]:
runtime.cgocall(0x40bc1e0, 0xc000052c70, 0x40ea1e0)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000052c40 sp=0xc000052c08 pc=0x400484e

github.com/samoslab/nebula/vendor/github.com/Nik-U/pbc._Cfunc_pairing_init_pbc_param(0x8000000, 0x723de50)
        _cgo_gotypes.go:1439 +0x41 fp=0xc000052c70 sp=0xc000052c40 pc=0x40b4171
github.com/samoslab/nebula/vendor/github.com/Nik-U/pbc.NewPairing.func1(0x8000000, 0x723de50)
        /Users/lijt/go/src/github.com/samoslab/nebula/vendor/github.com/Nik-U/pbc/pairing.go:65 +0x8f fp=0xc000052ca8 sp=0xc000052c70 pc=0x40b7faf
github.com/samoslab/nebula/vendor/github.com/Nik-U/pbc.NewPairing(0xc0000c4068, 0x166)
        /Users/lijt/go/src/github.com/samoslab/nebula/vendor/github.com/Nik-U/pbc/pairing.go:65 +0x44 fp=0xc000052cd0 sp=0xc000052ca8 pc=0x40b6204
github.com/samoslab/nebula/vendor/github.com/Nik-U/pbc.NewPairingFromString(0x40fd037, 0x166, 0x1e3, 0xc000396000, 0x0)
        /Users/lijt/go/src/github.com/samoslab/nebula/vendor/github.com/Nik-U/pbc/pairing.go:84 +0x6f fp=0xc000052d08 sp=0xc000052cd0 pc=0x40b628f
github.com/samoslab/nebula/util/filecheck.GenMetadata(0xc000297d00, 0x33, 0xc000040000, 0x40fd037, 0x166, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/lijt/go/src/github.com/samoslab/nebula/util/filecheck/filecheck.go:39 +0x1fb fp=0xc000052e10 sp=0xc000052d08 pc=0x40b917b
github.com/samoslab/nebula/util/filecheck.(*GenMetadataRunner).doGen(0xc00006a100, 0xc00029edc0)

go version go1.11.1 darwin/amd64
mac mojave 10.14.1

**Comment by Nik-U** [comment]
Based on [the OS X signal handler](https://github.com/golang/go/blob/master/src/runtime/signal_darwin_amd64.go#L71) it looks like this is a case of something dereferencing a malformed pointer. My initial suspicion is that this is a bug in PBC that warrants deeper investigation. Do you have a minimum working example that reproduces this bug reliably?

**Comment by lijiangt** [comment]
The probability of occurrence is relatively low. I wrote a simple reproducible program. Generally, it will be at least tens of minutes. At most, it will crash for a few hours. Not only the mac platform, Ubuntu will crash, I have not tested it on the windows platform. Others have experienced similar crashes in Windows.

https://github.com/samoslab/nebula/blob/runner/util/filecheck/test/main.go

**Comment by Nik-U** [comment]
This was a nasty one. When calling functions like `NewPairingFromString` as in your example, a `Params` struct is first allocated, and then it is used to create the `Pairing` struct. Both of these have pointers to C structs that are initialized by PBC. However, since this `Params` object is not used for anything except instantiating this one pairing, the garbage collector determines that it is no longer accessible by Go. If the `Params` object is reaped, the finalizer will be called, and this will free the associated C pairing struct using PBC. If we're unfortunate enough to have this occur between lines 65 and 66 in pairing.go (i.e., while the `pairing_init_pbc_param` PBC function is executing), the parameters will be freed while they are still in use. This leads to the segfault.

I believe that this issue is fixed in d86aec0d94d5215ce76b54fcf3a45a2938916e66.

**Comment by lijiangt** [comment]
Wonderful, it won’t crash now, I haven’t crashed after 15 hours of testing.
